In [1]:
import numpy as np

## Dataset 1

__X__ has 3 continuous features, __Y__ is a single number.

If x_0 > 0, y = x_1. Otherwise, y = x_2.

In [2]:
datasize = 10000

x = np.random.uniform(low=0, high=1, size=(datasize, 3))
y = np.zeros((datasize, 1))
for i in range(datasize):
    y[i, 0] = x[i, 1] if x[i, 0] > 0.5 else x[i, 2]

for i in range(5):
    print(x[i], y[i])

[0.55060268 0.39245848 0.71952362] [0.39245848]
[0.91109791 0.72489333 0.92864347] [0.72489333]
[0.27671705 0.43487896 0.92598379] [0.92598379]
[0.74621235 0.9549078  0.36308088] [0.9549078]
[0.83513382 0.01825462 0.09916959] [0.01825462]


## Dataset 2

__X__ is the same as above, __Y__ is either -0,2 or 0,5.

In [13]:
datasize = 10000

x = np.random.uniform(low=0, high=1, size=(datasize, 3))
y = np.zeros((datasize, 1))
for i in range(datasize):
    y[i, 0] = 0 if x[i, 0] > 0.5 else 0.999

for i in range(5):
    print(x[i], y[i])

[0.6768646  0.40493341 0.42927454] [0.]
[0.02509002 0.81685613 0.753418  ] [0.999]
[0.07716709 0.78388174 0.87425364] [0.999]
[0.03427334 0.83868677 0.02956642] [0.999]
[0.64022978 0.57766649 0.0621873 ] [0.]


In [3]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Activation, GRU

Using TensorFlow backend.


In [14]:
model = Sequential([
    Dense(3, input_shape=(3,)),
    #Activation('relu'),
    Dense(3),
    Activation('relu'),
    Dense(1),
    Activation('relu'),
])

model.compile(optimizer='adam',
              loss='mse')

In [15]:
model.fit(x, y, epochs=100, batch_size=32)

Epoch 1/100
10000/10000 [==============================] - 0s 48us/step - loss: 0.2522
Epoch 2/100
10000/10000 [==============================] - 0s 28us/step - loss: 0.0996
Epoch 3/100
10000/10000 [==============================] - 0s 28us/step - loss: 0.0417
Epoch 4/100
10000/10000 [==============================] - 0s 28us/step - loss: 0.0359
Epoch 5/100
10000/10000 [==============================] - 0s 28us/step - loss: 0.0318
Epoch 6/100
10000/10000 [==============================] - 0s 28us/step - loss: 0.0279
Epoch 7/100
10000/10000 [==============================] - 0s 28us/step - loss: 0.0239
Epoch 8/100
10000/10000 [==============================] - 0s 28us/step - loss: 0.0203
Epoch 9/100
10000/10000 [==============================] - 0s 28us/step - loss: 0.0171
Epoch 10/100
10000/10000 [==============================] - 0s 30us/step - loss: 0.0146
Epoch 11/100
10000/10000 [==============================] - 0s 28us/step - loss: 0.0129
Epoch 12/100
10000/10000 [===============

10000/10000 [==============================] - 0s 23us/step - loss: 0.0023
Epoch 95/100
10000/10000 [==============================] - 0s 23us/step - loss: 0.0027
Epoch 96/100
10000/10000 [==============================] - 0s 23us/step - loss: 0.0021
Epoch 97/100
10000/10000 [==============================] - 0s 23us/step - loss: 0.0020
Epoch 98/100
10000/10000 [==============================] - 0s 25us/step - loss: 0.0020
Epoch 99/100
10000/10000 [==============================] - 0s 25us/step - loss: 0.0023
Epoch 100/100
10000/10000 [==============================] - 0s 25us/step - loss: 0.0020


In [12]:
np.c_[model.predict(x[:10]), y[:10]]

array([[0.01273532, 0.        ],
       [0.        , 0.        ],
       [0.76038051, 0.999     ],
       [1.16355634, 0.999     ],
       [0.03889084, 0.        ],
       [0.82795948, 0.999     ],
       [0.50485015, 0.999     ],
       [0.        , 0.        ],
       [0.95678228, 0.999     ],
       [0.        , 0.        ]])

In [70]:
model.get_weights()

[array([[ 1.4006951e+00, -8.9346784e-01, -1.2880635e-01],
        [-9.7655207e-03,  2.1995849e-03, -2.6192212e-01],
        [ 4.3099943e-05,  4.3041253e-01, -6.2307787e-01]], dtype=float32),
 array([-0.59451354,  0.47829336,  0.        ], dtype=float32),
 array([[-1.4812533 , -0.79973626,  1.6194167 ],
        [ 0.5627546 , -0.3893392 ,  0.83054477],
        [ 0.21814847,  0.46995878,  0.595737  ]], dtype=float32),
 array([ 0.34383178,  0.        , -0.10780862], dtype=float32),
 array([[ 2.0093389],
        [ 0.727564 ],
        [-1.3644478]], dtype=float32),
 array([0.16349046], dtype=float32)]